name: huntcraft
version: '${version}'
main: de.cloudypanda.main.Huntcraft
api-version: '1.21'
load: STARTUP
authors: [ Pxndarino ]

commands:
  huntcraft-submit:
    description: 'Submit command for the advent calendar'
    usage: '/huntcraft-submit'
    aliases: [ hcs,submit ]
  huntcraft-leaderboard:
    description: 'Open the leaderboard for the advent calendar'
    usage: '/huntcraft-leaderboard'
    aliases: [ hcl,leaderboard ]